name: vpn
description: PVNetwork client.
publish_to: "none"
version: 0.3.0+30

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: 10.3.1
  file_picker: 11.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/brand/
